language: node_js
sudo: required
addons:
  chrome: stable

node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build devicewise-angular
  - ng test devicewise-angular
