name: deviceWISE Angular CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 📑 Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 🟢 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🟢 Install node modules
        run: npm install

      - name: 🔨 Build deviceWISE Angular
        run: npm run build devicewise-angular

      - name: 🧹 Lint deviceWISE Angular
        run: npm run lint devicewise-angular

      - name: 🔨 Build deviceWISE Angular Demo
        run: npm run build

      - name: 🧹 Lint deviceWISE Angular Demo
        run: npm run lint devicewise-angular

      - name: 🧹 Lint deviceWISE Angular Demo
        if: ${{ always() }}
        run: npm run publish

      - name: ⌚ Check if version has been updated
        id: check
        uses: EndBug/version-check@v1

      - name: 🔺 NPM Publish
        if: steps.check.outputs.changed == 'true'
        run: npm run publish